### ISSUE TITLE
@Template annotation on controller which is lazy service is broken in Symfony 2.3.3

### ISSUE THREAD

**Issue by maxromanovsky** [sensiolabs/SensioFrameworkExtraBundle#234]
`@Template` annotation works fine for me on Symfony 2.3.2, but breaks in Symfony 2.3.3 with error:

```
The controller must return a response (Array() given).
```

Controller:

``` php
<?php

namespace Foo\WebsiteBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration as Mvc;

/**
 * @Mvc\Route(service="foo_website.controller.index")
 */
class IndexController
{
    /**
     * @Mvc\Route("/")
     * @Mvc\Template
     */
    public function indexAction()
    {
        return [];
    }
}
```

Services configuration:

``` yaml
parameters:
   foo_website.controller.index.class: Foo\WebsiteBundle\Controller\IndexController

services:
    foo_website.controller.index:
        class: %foo_website.controller.index.class%
        lazy: true
```

Omitting `lazy: true` helps to resolve the issue.
