### ISSUE TITLE
New @Template engine configuration

### ISSUE THREAD

**Issue by kralos** [sensiolabs/SensioFrameworkExtraBundle#403]
I was considering adding the ability to configure the templating engine at various levels.

I have written the docs for what I have been considering implementing. Let me know what you think.

# Summary

## Configurable default engine

```yaml
sensio_framework_extra:
    view:
        annotations: true
        default_engine: twig
```

@fabpot mentioned in #226 that this would break any bundles relying on a default of `twig`. This is a potential problem. We could warn anyone wanting to configure an alternative default that they will need to provide their own templates for any other bundles they are using, not that I would wish that kind of maintenance on anyone. Any other comments on this part of the feature? Maybe providing controller level `@Template` would solve this problem sufficiently for people with alternate templating engines? @rafalwrzeszcz ?

## Format specific templating engines

```yaml
sensio_framework_extra:
    view:
        annotations: true
        default_engine: twig
        default_format_engines:
            # html: twig # because of default_engine
            csv: php
            json: php
```

## Controller specific templating engines

```php
/**
 * @Template(engine="php")
 */
class DefaultController
{
    // ...
}
```

## Controller/Format specific templating engines

```php
/**
 * @Template(format_engines={
 *      "csv" = "php",
 *      "json" = "php",
 * })
 */
class DefaultController
{
    // ...
}
```

## Action specific templating engines

```php
/**
 * @Template(engine="php")
 */
public function showAction($id)
{
    // ...
}
```

## Action/Format specific templating engines

This could be used for anyone wanting to migrate their application one action at a time or for someone with specific needs on a particular action.

```php
/**
 * @Template(format_engines={
 *      "csv" = "php",
 *      "json" = "php",
 * })
 */
public function showAction($id)
{
    // ...
}
```

# Motivation

I came across these need to specify engines based on `_format` when building a system that supports content negotiation for `html`, `json`, `csv`. I found serialization of `html` with `twig` is awesome however `json` and `csv` are challenging. PHP already has great support for building csv's in its `fputcsv` function which can be combined with an output stream to achieve view serialization.

Please see:

* https://github.com/sensiolabs/SensioFrameworkExtraBundle/compare/master...assimtech:feature-template-config
* http://framework-extra-bundle.assimtech.com/annotations/view.html

Related: #226
