### ISSUE TITLE
Don't execute listeners for disabled features

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioFrameworkExtraBundle#427]
In a personal Symfony project I've disabled a lot of features that I don't need, including the entire security system (and the SecurityBundle) and the translation service.

However, SensioFrameworkExtraBundle still calls to some listeners related to Security and Translation:

![symfony-timeline](https://cloud.githubusercontent.com/assets/73419/18419663/7f828418-7860-11e6-94d6-073f190c477b.png)

I know that it says `0 ms` time ... but I don't trust that. The only code that takes `0 ms` to execute is the code that it's not executed.

So, should SensioFrameworkExtraBundle check if security is enabled, translation is enabled, etc. before enabling those listeners? Thanks!

**Comment by fabpot** [comment]
Sounds like a plan.

**Comment by Koc** [comment]
Does `TranslationListener` come from SensioFrameworkExtraBundle?

**Comment by iltar** [comment]
It would be nice to have a bit more control over the features, not only which listeners are active, but also which parameter converters are enabled by default.

**Comment by fabpot** [comment]
You can disable annotation support (and so the associated listener) via configuration:

```yaml
        sensio_framework_extra:
            router:      { annotations: true }
            request:     { converters: true, auto_convert: true }
            view:        { annotations: true }
            cache:       { annotations: true }
            security:    { annotations: true }
            psr_message: { enabled: false } # Defaults to true if the PSR-7 bridge is installed

```

Indeed, being able to lazy-load them would be a good idea, and being able to have more control over the param converters as well.
