### ISSUE TITLE
Don't create services for disabled features

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioFrameworkExtraBundle#463]
In my app I have the following config:

```yaml
sensio_framework_extra:
    cache:       { annotations: true }
    psr_message: { enabled: false }
    request:     { converters: false, auto_convert: false }
    router:      { annotations: true }
    security:    { annotations: false }
    view:        { annotations: false }
```

`view` is one of the disabled features, because I don't use `@Template()`

However, in the dumped container in production, I can see that this service related to `@Template()` is enabled:

```php
'sensio_framework_extra.view.guesser' => 'getSensioFrameworkExtra_View_GuesserService',

// ...

protected function getSensioFrameworkExtra_View_GuesserService()
{
    return $this->services['sensio_framework_extra.view.guesser'] = new \Sensio\Bundle\FrameworkExtraBundle\Templating\TemplateGuesser($this->get('kernel'));
}
```
