### ISSUE TITLE
Custom ParamConverter bug (cant' get ride of Doctrine converter)

### ISSUE THREAD

**Issue by skornev** [sensiolabs/SensioFrameworkExtraBundle#483]
I cant' find the way to get ride of Doctrine converter.
Documentation says:

If an explicit converter choice was made with @paramconverter(converter="name") the converter with the given name is chosen.
But it still calls both custom and doctrine converter.

**Comment by jakzal** [comment]
Could you show us the method signature and how you configured your param converter(s)?

**Comment by jakzal** [comment]
Possibly a duplicate of #472

**Comment by skornev** [comment]
`@ParamConverter(name="id", converter="custom_converter", class="AppBundle\Entity\MyEntity")
`services ()

```
   custom_converter:
        class: AppBundle\Request\ParamConverter\CustomConverter
        tags:
            - { name: request.param_converter, priority: -2, converter: custom_converter }
```

Set priority="false" does not help either.
