### ISSUE TITLE
Activating Auto ParamConverter with SF4

### ISSUE THREAD

**Issue by juliusstoerrle** [sensiolabs/SensioFrameworkExtraBundle#531]
Hi, just switched to SF4 with Flex. How can I activate the Automatic Param Conversion as described in the docs? (http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html)

The docs want me to put following in my config:
```
# app/config/config.yml
sensio_framework_extra:
    request:
        converters: true
        auto_convert: true
```

I placed those lines at the head of the services.yaml, as the old config doesn't exist anymore (as you know). I also did some research in my old project files and wasn't able to find those config settings in the old config.yaml file.

**Comment by fre5h** [comment]
@juliusstoerrle converters are enabled by default. I think you are using autowiring and autoconfiguring and wonder why your converters do not work with Sf4. Am I right?

**Comment by juliusstoerrle** [comment]
@fre5h Yes, thats right!

**Comment by fre5h** [comment]
Because I have same issue. Looks like autoconfiguring doesn't work for param converters. My param converters implement Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterInterface so they must be autoconfigured as services by default. But they don't

I solved this issue by manually setting tag for my converters

```yaml
    App\Request\ParamConverter\:
        resource: '../src/Request/ParamConverter/'
        tags:
            - 'request.param_converter'
```
