### ISSUE TITLE
Unable to replace alias "sensio_framework_extra.converter.listener" after upgrade to 5.1

### ISSUE THREAD

**Issue by Soullivaneuh** [sensiolabs/SensioFrameworkExtraBundle#544]
Just after an upgrade of this package from `v5.0.1` to `v5.1.3`, I have this error at the end of composer script.

```
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]   
  Unable to replace alias "sensio_framework_extra.converter.listener" with ac  
  tual definition "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConv  
  erterListener".                                                              
                                                                               

                                                                               
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
  You have requested a non-existent service "Sensio\Bundle\FrameworkExtraBund  
  le\EventListener\ParamConverterListener".                                    
                                                                               

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                                   
  [RuntimeException]                                                               
  An error occurred when executing the "'cache:clear --no-warmup'" command:        
                                                                                   
    [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]     
    Unable to replace alias "sensio_framework_extra.converter.listener" with ac    
    tual definition "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConv    
    erterListener".                                                                
                                                                                   
                                                                                   
    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]     
    You have requested a non-existent service "Sensio\Bundle\FrameworkExtraBund    
    le\EventListener\ParamConverterListener".                                      
```

Rollbacking to `v5.0.1` "solves" the issue. It seems some BC break was introduced here.

**Comment by Soullivaneuh** [comment]
Found why. I added those line before:

```yaml
services:
    # Needed Sensio aliases waiting this commit to be released: https://github.com/FriendsOfSymfony/FOSRestBundle/commit/8c0d01de9
    sensio_framework_extra.converter.listener: '@Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener'
    sensio_framework_extra.view.listener: '@Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener'
```

Removing them solve the issue.

I don't know if this should be considered as a BC break.
