### ISSUE TITLE
DoctrineParamConverter ignores type mapping

### ISSUE THREAD

**Issue by MatTheCat** [sensiolabs/SensioFrameworkExtraBundle#584]
As my company is using MongoDB I registered a paramconverter as such:

```yaml
sib.converter.doctrine.odm:
    class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
    arguments:
        - '@doctrine_mongodb'
    tags:
        - name: request.param_converter
          converter: doctrine.odm
```

Problem is, MongoDB cares about type and won't return anything if you query an integer field  with a string value. Would it be a way to convert the request value before running the query?
