### ISSUE TITLE
Confusing behavior for DoctrineParamConverter when a param is explicitly null

### ISSUE THREAD

**Issue by stof** [sensiolabs/SensioFrameworkExtraBundle#651]
I have a case looking like that:

```
class IndividualMissionController
{
    public function createAction(Request $request, Member $owner, ?IndividualMission $parentMission = null)
    {
    }
}
```

And I have 2 routes defined on it:

```
coaching_individual_mission_create:
    path: /missions/create
    defaults:
        _controller: Incenteev\WebBundle\Controller\Coaching\IndividualMissionController::createAction
    methods: [GET, POST]

coaching_individual_mission_reuse:
    path: /missions/{parentMission}/reuse
    defaults:
        _controller: Incenteev\WebBundle\Controller\Coaching\IndividualMissionController::createAction
    methods: [GET, POST]
    requirements:
        parentMission: '%incenteev.router.requirement.uuid%'
```

The `coaching_individual_mission_reuse` works fine.
But the `coaching_individual_mission_create` would try to load a parent mission by owner in this case, due to the fallback by criteria when loading by identifier does not work.
Even setting `parentMission` to `null` explicitly in the route defaults does not allow to avoid that. The workaround is to do `@ParamConverter("parentMission", options={"id": "parentMission"})` to force loading by id only, as it will disable the loading by criteria when using an explicit id.

I think it should at least do the same disabling when the request has explicitly an attribute set to `null` matching the default id retrieval (i.e. `getIdentifier` returning `null` rather than `false`). What do you think about that idea ?
Another option which would work for me would be a way to disable the criteria loading globally (maybe with a way to opt-in again in the annotation), as I'm always loading by identifier in the project.
