### ISSUE TITLE
ParamConverter with Symfony5 returns always a NotFound Exception (object not found)

### ISSUE THREAD

**Issue by astronati** [sensiolabs/SensioFrameworkExtraBundle#711]
The upgrade to Symfony5 does not allow the usage of the ParamConverter.

sensio_framework_extra.yaml
```
sensio_framework_extra:
    router:
        annotations: false
    request:
        converters: true
        auto_convert: false
    psr_message:
        enabled: false
```

```
@ParamConverter("blogPost", options={"mapping": {"blogPostID": "blogPostID"}})
```

Returns an error even if the action that uses that is not called.

```
App\Domain\Entity\BlogPost object not found by the @ParamConverter annotation.
```
